In [ ]:
# File Name: Cleaning&Analysis.ipynb

# Objective: To clean and analyze the scraped basketball data, including data for MVPs, players, and teams. This analysis will help in making predictions and further insights.

# Author: PARAM JASWAL

# Programming language: Python

# Libraries: Pandas, NumPy

# Total Parts: 3 (Loading and cleaning MVP data, player data, and team data; Merging data for analysis)

# complete project avalible at: https://github.com/param10/NBa_MVP_Prediction

## Importing Libraries

In [68]:
import pandas as pd
import numpy as np

## Loading and Cleaning MVP Data

In [69]:
mvps = pd.read_csv("/Users/paramjaswal/Desktop/NBa/mvps.csv")
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Bob Pettit,23,STL,33.0,33.0,80,0.413,72,...,16.2,2.6,NaN,NaN,0.429,NaN,0.736,13.8,0.236,1956
1,1,2,Paul Arizin,27,PHW,21.0,21.0,80,0.263,72,...,7.5,2.6,NaN,NaN,0.448,NaN,0.810,12.2,0.214,1956
2,2,3,Bob Cousy,27,BOS,11.0,11.0,80,0.138,72,...,6.8,8.9,NaN,NaN,0.360,NaN,0.844,6.8,0.119,1956
3,3,4,Mel Hutchins,27,FTW,9.0,9.0,80,0.113,66,...,7.5,2.7,NaN,NaN,0.425,NaN,0.643,4.4,0.095,1956
4,4,5T,Dolph Schayes,27,SYR,2.0,2.0,80,0.025,72,...,12.4,2.8,NaN,NaN,0.387,NaN,0.858,11.8,0.225,1956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1018,1018,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
1019,1019,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
1020,1020,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
1021,1021,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
1022,1022,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [70]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]
mvps

             Player  Year  Pts Won  Pts Max  Share
0        Bob Pettit  1956     33.0       80  0.413
1       Paul Arizin  1956     21.0       80  0.263
2         Bob Cousy  1956     11.0       80  0.138
3      Mel Hutchins  1956      9.0       80  0.113
4     Dolph Schayes  1956      2.0       80  0.025
...             ...   ...      ...      ...    ...
1018  Stephen Curry  2022      4.0     1000  0.004
1019     Chris Paul  2022      2.0     1000  0.002
1020  DeMar DeRozan  2022      1.0     1000  0.001
1021   Kevin Durant  2022      1.0     1000  0.001
1022   LeBron James  2022      1.0     1000  0.001

[1023 rows x 5 columns]

## Loading and Cleaning Player Data

We load the player statistics, remove unnecessary columns, and clean up the data.

In [71]:
players = pd.read_csv("/Users/paramjaswal/Desktop/NBa/players.csv")
players

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Paul Arizin*,SF,27,PHW,72,NaN,37.8,8.6,...,NaN,NaN,7.5,2.6,NaN,NaN,NaN,3.9,24.2,1956
1,1,2,Jesse Arnelle,PF,22,FTW,31,NaN,13.2,1.7,...,NaN,NaN,5.5,0.6,NaN,NaN,NaN,1.9,4.7,1956
2,2,3,Dick Atha,SG,24,NYK,25,NaN,11.5,1.4,...,NaN,NaN,1.7,1.3,NaN,NaN,NaN,1.6,3.7,1956
3,3,4,Jim Baechtold,SF,28,NYK,70,NaN,24.8,3.8,...,NaN,NaN,3.1,2.3,NaN,NaN,NaN,2.2,11.0,1956
4,4,5,Ernie Barrett,SG,26,BOS,72,NaN,20.2,2.9,...,NaN,NaN,3.4,2.4,NaN,NaN,NaN,2.6,7.0,1956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27168,27168,601,Thaddeus Young,PF,33,TOR,26,0.0,18.3,2.6,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
27169,27169,602,Trae Young,PG,23,ATL,76,76.0,34.9,9.4,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
27170,27170,603,Omer Yurtseven,C,23,MIA,56,12.0,12.6,2.3,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
27171,27171,604,Cody Zeller,C,29,POR,27,0.0,13.1,1.9,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
27172,27172,605,Ivica Zubac,C,24,LAC,76,76.0,24.4,4.1,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [72]:
del players["Unnamed: 0"]
del players["Rk"]

players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Paul Arizin*,SF,27,PHW,72,NaN,37.8,8.6,19.1,0.448,...,NaN,NaN,7.5,2.6,NaN,NaN,NaN,3.9,24.2,1956
1,Jesse Arnelle,PF,22,FTW,31,NaN,13.2,1.7,5.3,0.317,...,NaN,NaN,5.5,0.6,NaN,NaN,NaN,1.9,4.7,1956
2,Dick Atha,SG,24,NYK,25,NaN,11.5,1.4,3.5,0.409,...,NaN,NaN,1.7,1.3,NaN,NaN,NaN,1.6,3.7,1956
3,Jim Baechtold,SF,28,NYK,70,NaN,24.8,3.8,9.9,0.386,...,NaN,NaN,3.1,2.3,NaN,NaN,NaN,2.2,11.0,1956
4,Ernie Barrett,SG,26,BOS,72,NaN,20.2,2.9,7.4,0.388,...,NaN,NaN,3.4,2.4,NaN,NaN,NaN,2.6,7.0,1956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27168,Thaddeus Young,PF,33,TOR,26,0.0,18.3,2.6,5.5,0.465,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
27169,Trae Young,PG,23,ATL,76,76.0,34.9,9.4,20.3,0.460,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
27170,Omer Yurtseven,C,23,MIA,56,12.0,12.6,2.3,4.4,0.526,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
27171,Cody Zeller,C,29,POR,27,0.0,13.1,1.9,3.3,0.567,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
27172,Ivica Zubac,C,24,LAC,76,76.0,24.4,4.1,6.5,0.626,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

### Handling Players with Multiple Teams

In [73]:
players["Player"] = players["Player"].str.replace("*", "", regex=False)
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Paul Arizin,SF,27,PHW,72,NaN,37.8,8.6,19.1,0.448,...,NaN,NaN,7.5,2.6,NaN,NaN,NaN,3.9,24.2,1956
1,Jesse Arnelle,PF,22,FTW,31,NaN,13.2,1.7,5.3,0.317,...,NaN,NaN,5.5,0.6,NaN,NaN,NaN,1.9,4.7,1956
2,Dick Atha,SG,24,NYK,25,NaN,11.5,1.4,3.5,0.409,...,NaN,NaN,1.7,1.3,NaN,NaN,NaN,1.6,3.7,1956
3,Jim Baechtold,SF,28,NYK,70,NaN,24.8,3.8,9.9,0.386,...,NaN,NaN,3.1,2.3,NaN,NaN,NaN,2.2,11.0,1956
4,Ernie Barrett,SG,26,BOS,72,NaN,20.2,2.9,7.4,0.388,...,NaN,NaN,3.4,2.4,NaN,NaN,NaN,2.6,7.0,1956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27168,Thaddeus Young,PF,33,TOR,26,0.0,18.3,2.6,5.5,0.465,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
27169,Trae Young,PG,23,ATL,76,76.0,34.9,9.4,20.3,0.460,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
27170,Omer Yurtseven,C,23,MIA,56,12.0,12.6,2.3,4.4,0.526,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
27171,Cody Zeller,C,29,POR,27,0.0,13.1,1.9,3.3,0.567,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
27172,Ivica Zubac,C,24,LAC,76,76.0,24.4,4.1,6.5,0.626,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [74]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row


players = players.groupby(["Player", "Year"]).apply(single_row)
players.head(20)

                                 Player Pos  Age   Tm   G    GS    MP   FG  \
Player        Year
A.C. Green    1986 7008      A.C. Green  PF   22  LAL  82   1.0  18.8  2.5
              1987 7392      A.C. Green  PF   23  LAL  79  72.0  28.4  4.0
              1988 7778      A.C. Green  PF   24  LAL  82  64.0  32.1  3.9
              1989 8212      A.C. Green  PF   25  LAL  82  82.0  30.6  4.9
              1990 8657      A.C. Green  PF   26  LAL  82  82.0  33.0  4.7
              1991 9134      A.C. Green  PF   27  LAL  82  21.0  26.4  3.1
              1992 9584      A.C. Green  PF   28  LAL  82  53.0  35.4  4.7
              1993 10026     A.C. Green  PF   29  LAL  82  55.0  34.4  4.6
              1994 10494     A.C. Green  PF   30  PHO  82  55.0  34.5  5.7
              1995 10963     A.C. Green  SF   31  PHO  82  52.0  32.8  3.8
              1996 11440     A.C. Green  SF   32  PHO  82  36.0  25.8  2.6
              1997 11995     A.C. Green  PF   33  DAL  83  73.0  30.0  2.8
              1998 12561     A.C. Green  PF   34  DAL  82  68.0  32.3  3.0
              1999 13099     A.C. Green  PF   35  DAL  50  35.0  18.5  2.2
              2000 13607     A.C. Green  PF   36  LAL  82  82.0  23.5  2.1
              2001 14106     A.C. Green  PF   37  MIA  82   1.0  17.2  1.8
A.J. Bramlett 2000 13485  A.J. Bramlett   C   23  CLE   8   0.0   7.6  0.5
A.J. English  1991 9098    A.J. English  SG   23  WSB  70  12.0  20.6  3.6
              1992 9550    A.J. English  SG   24  WSB  81   6.0  20.6  4.5
A.J. Guyton   2001 14109    A.J. Guyton  PG   22  CHI  33   8.0  19.1  2.4

                           FGA    FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV  \
Player        Year                     ...
A.C. Green    1986 7008    4.7  0.539  ...  2.0  2.7  4.6  0.7  0.6  0.6  1.2
              1987 7392    7.4  0.538  ...  2.7  5.1  7.8  1.1  0.9  1.0  1.3
              1988 7778    7.8  0.503  ...  3.0  5.7  8.7  1.1  1.1  0.5  1.5
              1989 8212    9.2  0.529  ...  3.1  5.9  9.0  1.3  1.1  0.7  1.5
              1990 8657    9.8  0.478  ...  3.2  5.5  8.7  1.1  0.8  0.6  1.4
              1991 9134    6.6  0.476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2
              1992 9584    9.8  0.476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4
              1993 10026   8.6  0.537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4
              1994 10494  11.3  0.502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2
              1995 10963   7.5  0.504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4
              1996 11440   5.4  0.484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0
              1997 11995   5.8  0.483  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9
              1998 12561   6.5  0.453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8
              1999 13099   5.1  0.422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4
              2000 13607   4.7  0.447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6
              2001 14106   4.0  0.444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5
A.J. Bramlett 2000 13485   2.6  0.190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4
A.J. English  1991 9098    8.2  0.439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6
              1992 9550   10.4  0.433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1
A.J. Guyton   2001 14109   5.8  0.406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7

                           PF   PTS  Year
Player        Year
A.C. Green    1986 7008   2.8   6.4  1986
              1987 7392   2.2  10.8  1987
              1988 7778   2.5  11.4  1988
              1989 8212   2.1  13.3  1989
              1990 8657   2.5  12.9  1990
              1991 9134   1.4   9.1  1991
              1992 9584   1.7  13.6  1992
              1993 10026  1.8  12.8  1993
              1994 10494  1.7  14.7  1994
              1995 10963  1.8  11.2  1995
              1996 11440  1.7   7.5  1996
              1997 11995  1.7   7.2  1997
              1998 12561  1.9   7.3  1998
              1999 13099  1.4   4.9  1999
              2000 13607  1.5   5.0  2000
              2001 14106  1.5   4.5  2001
A.J. Bramlett 2000 13485  1.6   1.0  2000
A.J. English  1991 9098   1.8   8.8  1991
              1992 9550   2.0  10.9  1992
A.J. Guyton   2001 14109  1.1   6.0  2001

[20 rows x 30 columns]

## Merging MVP and Player Data

In [75]:
players = players.reset_index(drop=True)
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,A.C. Green,PF,22,LAL,82,1.0,18.8,2.5,4.7,0.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
1,A.C. Green,PF,23,LAL,79,72.0,28.4,4.0,7.4,0.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
2,A.C. Green,PF,24,LAL,82,64.0,32.1,3.9,7.8,0.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
3,A.C. Green,PF,25,LAL,82,82.0,30.6,4.9,9.2,0.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
4,A.C. Green,PF,26,LAL,82,82.0,33.0,4.7,9.8,0.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,Željko Rebrača,C,29,DET,74,4.0,15.9,2.6,5.1,0.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
22190,Željko Rebrača,C,30,DET,30,12.0,16.3,2.7,4.8,0.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
22191,Željko Rebrača,C,31,ATL,24,2.0,11.4,1.4,3.2,0.442,...,1.0,1.5,2.4,0.3,0.2,0.5,0.7,2.2,3.8,2004
22192,Željko Rebrača,C,32,LAC,58,2.0,16.0,2.3,4.0,0.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
22193,Željko Rebrača,C,33,LAC,29,2.0,14.2,1.8,3.3,0.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [76]:
combined_data = players.merge(mvps, how="outer", on = ["Player", "Year"])
combined_data

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,22.0,LAL,82.0,1.0,18.8,2.5,4.7,0.539,...,0.7,0.6,0.6,1.2,2.8,6.4,1986,NaN,NaN,NaN
1,A.C. Green,PF,23.0,LAL,79.0,72.0,28.4,4.0,7.4,0.538,...,1.1,0.9,1.0,1.3,2.2,10.8,1987,NaN,NaN,NaN
2,A.C. Green,PF,24.0,LAL,82.0,64.0,32.1,3.9,7.8,0.503,...,1.1,1.1,0.5,1.5,2.5,11.4,1988,NaN,NaN,NaN
3,A.C. Green,PF,25.0,LAL,82.0,82.0,30.6,4.9,9.2,0.529,...,1.3,1.1,0.7,1.5,2.1,13.3,1989,NaN,NaN,NaN
4,A.C. Green,PF,26.0,LAL,82.0,82.0,33.0,4.7,9.8,0.478,...,1.1,0.8,0.6,1.4,2.5,12.9,1990,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22190,Željko Rebrača,C,30.0,DET,30.0,12.0,16.3,2.7,4.8,0.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,NaN,NaN,NaN
22191,Željko Rebrača,C,31.0,ATL,24.0,2.0,11.4,1.4,3.2,0.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,NaN,NaN,NaN
22192,Željko Rebrača,C,32.0,LAC,58.0,2.0,16.0,2.3,4.0,0.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
22193,Željko Rebrača,C,33.0,LAC,29.0,2.0,14.2,1.8,3.3,0.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN
22194,George Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1981,3.0,690.0,0.004

In [77]:
combined_data[combined_data["Pts Won"] > 0]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
168,Adrian Dantley,SF,25.0,UTA,80.0,NaN,42.7,11.4,20.3,0.559,...,4.0,1.4,0.2,3.5,3.1,30.7,1981,15.0,690.0,0.022
169,Adrian Dantley,SF,26.0,UTA,81.0,81.0,39.8,11.2,19.6,0.570,...,4.0,1.2,0.2,3.7,3.1,30.3,1982,7.0,690.0,0.010
171,Adrian Dantley,SF,28.0,UTA,79.0,79.0,37.8,10.2,18.2,0.558,...,3.9,0.8,0.1,3.3,2.5,30.6,1984,88.0,760.0,0.116
173,Adrian Dantley,SF,30.0,UTA,76.0,75.0,36.1,10.8,19.1,0.563,...,3.5,0.8,0.1,3.0,2.7,29.8,1986,2.0,780.0,0.003
175,Adrian Dantley,SF,32.0,DET,69.0,50.0,31.1,6.4,12.5,0.514,...,2.5,0.6,0.1,2.0,2.1,20.0,1988,1.0,800.0,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21986,World B. Free,SG,30.0,CLE,75.0,71.0,31.7,8.3,18.8,0.445,...,3.0,1.3,0.1,2.1,2.9,22.3,1984,1.0,760.0,0.001
21987,World B. Free,SG,31.0,CLE,71.0,50.0,31.7,8.6,18.7,0.459,...,4.5,1.1,0.2,2.0,2.3,22.5,1985,2.0,780.0,0.003
22024,Yao Ming,C,23.0,HOU,82.0,82.0,32.8,6.5,12.5,0.522,...,1.5,0.3,1.9,2.5,3.3,17.5,2004,1.0,1230.0,0.001
22029,Yao Ming,C,28.0,HOU,77.0,77.0,33.6,7.4,13.4,0.548,...,1.8,0.4,1.9,3.0,3.3,19.7,2009,1.0,1210.0,0.001
22194,George Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1981,3.0,690.0,0.004

In [78]:
combined_data[["Pts Won", "Pts Max", "Share"]] = combined_data[["Pts Won", "Pts Max", "Share"]].fillna(0)
combined_data = combined_data.iloc[:-1]
combined_data

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,22.0,LAL,82.0,1.0,18.8,2.5,4.7,0.539,...,0.7,0.6,0.6,1.2,2.8,6.4,1986,0.0,0.0,0.0
1,A.C. Green,PF,23.0,LAL,79.0,72.0,28.4,4.0,7.4,0.538,...,1.1,0.9,1.0,1.3,2.2,10.8,1987,0.0,0.0,0.0
2,A.C. Green,PF,24.0,LAL,82.0,64.0,32.1,3.9,7.8,0.503,...,1.1,1.1,0.5,1.5,2.5,11.4,1988,0.0,0.0,0.0
3,A.C. Green,PF,25.0,LAL,82.0,82.0,30.6,4.9,9.2,0.529,...,1.3,1.1,0.7,1.5,2.1,13.3,1989,0.0,0.0,0.0
4,A.C. Green,PF,26.0,LAL,82.0,82.0,33.0,4.7,9.8,0.478,...,1.1,0.8,0.6,1.4,2.5,12.9,1990,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,Željko Rebrača,C,29.0,DET,74.0,4.0,15.9,2.6,5.1,0.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
22190,Željko Rebrača,C,30.0,DET,30.0,12.0,16.3,2.7,4.8,0.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
22191,Željko Rebrača,C,31.0,ATL,24.0,2.0,11.4,1.4,3.2,0.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
22192,Željko Rebrača,C,32.0,LAC,58.0,2.0,16.0,2.3,4.0,0.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
22193,Željko Rebrača,C,33.0,LAC,29.0,2.0,14.2,1.8,3.3,0.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [79]:
teams = pd.read_csv("/Users/paramjaswal/Desktop/NBa/teams.csv")
teams

,Unnamed: 0,Team,W,L,W/L%,GB,PS/G,PA/G,SRS,Year
0,0,Philadelphia Warriors*,45,27,0.625,—,103.1,98.8,3.82,1956
1,1,Boston Celtics*,39,33,0.542,6.0,106.0,105.3,0.72,1956
2,2,Syracuse Nationals*,35,37,0.486,10.0,96.9,96.9,0.17,1956
3,3,New York Knicks*,35,37,0.486,10.0,100.2,100.6,-0.20,1956
4,4,Fort Wayne Pistons*,37,35,0.514,—,94.4,93.7,0.45,1956
...,...,...,...,...,...,...,...,...,...,...
1502,1502,Memphis Grizzlies*,56,26,0.683,—,115.6,109.9,5.37,2022
1503,1503,Dallas Mavericks*,52,30,0.634,4.0,108.0,104.7,3.12,2022
1504,1504,New Orleans Pelicans*,36,46,0.439,20.0,109.3,110.3,-0.84,2022
1505,1505,San Antonio Spurs,34,48,0.415,22.0,113.2,113.0,0.02,2022
1506,1506,Houston Rockets,20,62,0.244,36.0,109.7,118.2,-8.26,2022

## Loading and Cleaning Team Data

In [80]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)
teams

,Unnamed: 0,Team,W,L,W/L%,GB,PS/G,PA/G,SRS,Year
0,0,Philadelphia Warriors,45,27,0.625,—,103.1,98.8,3.82,1956
1,1,Boston Celtics,39,33,0.542,6.0,106.0,105.3,0.72,1956
2,2,Syracuse Nationals,35,37,0.486,10.0,96.9,96.9,0.17,1956
3,3,New York Knicks,35,37,0.486,10.0,100.2,100.6,-0.20,1956
4,4,Fort Wayne Pistons,37,35,0.514,—,94.4,93.7,0.45,1956
...,...,...,...,...,...,...,...,...,...,...
1502,1502,Memphis Grizzlies,56,26,0.683,—,115.6,109.9,5.37,2022
1503,1503,Dallas Mavericks,52,30,0.634,4.0,108.0,104.7,3.12,2022
1504,1504,New Orleans Pelicans,36,46,0.439,20.0,109.3,110.3,-0.84,2022
1505,1505,San Antonio Spurs,34,48,0.415,22.0,113.2,113.0,0.02,2022
1506,1506,Houston Rockets,20,62,0.244,36.0,109.7,118.2,-8.26,2022

In [81]:
teams["Team"].unique()

array(['Philadelphia Warriors', 'Boston Celtics', 'Syracuse Nationals',
       'New York Knicks', 'Fort Wayne Pistons', 'Minneapolis Lakers',
       'St. Louis Hawks', 'Rochester Royals', 'Detroit Pistons',
       'Cincinnati Royals', 'Los Angeles Lakers', 'Chicago Packers',
       'San Francisco Warriors', 'Chicago Zephyrs', 'Philadelphia 76ers',
       'Baltimore Bullets', 'Chicago Bulls', 'Seattle SuperSonics',
       'San Diego Rockets', 'Milwaukee Bucks', 'Atlanta Hawks',
       'Phoenix Suns', 'Buffalo Braves', 'Cleveland Cavaliers',
       'Portland Trail Blazers', 'Golden State Warriors',
       'Houston Rockets', 'Kansas City-Omaha Kings', 'Capital Bullets',
       'Washington Bullets', 'New Orleans Jazz', 'Kansas City Kings',
       'New York Nets', 'San Antonio Spurs', 'Denver Nuggets',
       'Indiana Pacers', 'New Jersey Nets', 'San Diego Clippers',
       'Utah Jazz', 'Dallas Mavericks', 'Los Angeles Clippers',
       'Sacramento Kings', 'Charlotte Hornets', 'Miami Heat',
       'Orlando Magic', 'Minnesota Timberwolves', 'Toronto Raptors',
       'Vancouver Grizzlies', 'Washington Wizards', 'Memphis Grizzlies',
       'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

### Mapping Team Nicknames to Full Names

In [82]:
combined_data["Tm"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'DEN', 'ORL', 'NOH', 'TOR', 'SAC',
       'CHO', 'PHI', 'NOJ', 'POR', 'DET', 'OKC', 'UTA', 'MIL', 'VAN',
       'SEA', 'NJN', 'NOK', 'LAC', 'ATL', 'CHA', 'MEM', 'BUF', 'CIN',
       'SFW', 'PHW', 'SYR', 'NYK', 'BAL', 'STL', 'CHZ', 'NYN', 'SDC',
       'NOP', 'BRK', 'SAS', 'CHH', 'KCK', 'CHP', 'FTW', 'CAP', 'ROC',
       'SDR', 'MNL', 'KCO'], dtype=object)

In [83]:
nicknames = {}

with open("/Users/paramjaswal/Desktop/NBa/team_mapping.txt") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

## Merging All Data

In [84]:
nicknames

{'PHW': 'Philadelphia Warriors',
 'BOS': 'Boston Celtics',
 'SYR': 'Syracuse Nationals',
 'NYK': 'New York Knicks',
 'FTW': 'Fort Wayne Pistons',
 'MNL': 'Minneapolis Lakers',
 'STL': 'St. Louis Hawks',
 'ROC': 'Rochester Royals',
 'DET': 'Detroit Pistons',
 'CIN': 'Cincinnati Royals',
 'LAL': 'Los Angeles Lakers',
 'CHP': 'Chicago Packers',
 'SFW': 'San Francisco Warriors',
 'CHZ': 'Chicago Zephyrs',
 'PHI': 'Philadelphia 76ers',
 'BAL': 'Baltimore Bullets',
 'CHI': 'Chicago Bulls',
 'SEA': 'Seattle SuperSonics',
 'SDR': 'San Diego Rockets',
 'MIL': 'Milwaukee Bucks',
 'ATL': 'Atlanta Hawks',
 'PHO': 'Phoenix Suns',
 'BUF': 'Buffalo Braves',
 'CLE': 'Cleveland Cavaliers',
 'POR': 'Portland Trail Blazers',
 'GSW': 'Golden State Warriors',
 'HOU': 'Houston Rockets',
 'KCO': 'Kansas City-Omaha Kings',
 'CAP': 'Capital Bullets',
 'WSB': 'Washington Bullets',
 'NOJ': 'New Orleans Jazz',
 'KCK': 'Kansas City Kings',
 'NJN': 'New Jersey Nets',
 'SAS': 'San Antonio Spurs',
 'DEN': 'Denver Nuggets',
 'IND': 'Indiana Pacers',
 'SDC': 'San Diego Clippers',
 'UTA': 'Utah Jazz',
 'DAL': 'Dallas Mavericks',
 'LAC': 'Los Angeles Clippers',
 'SAC': 'Sacramento Kings',
 'CHO': 'Charlotte Hornets',
 'MIA': 'Miami Heat',
 'ORL': 'Orlando Magic',
 'MIN': 'Minnesota Timberwolves',
 'TOR': 'Toronto Raptors',
 'VAN': 'Vancouver Grizzlies',
 'WAS': 'Washington Wizards',
 'MEM': 'Memphis Grizzlies',
 'NOH': 'New Orleans Hornets',
 'CHA': 'Charlotte Bobcats',
 'NOK': 'New Orleans/Oklahoma City Hornets',
 'OKC': 'Oklahoma City Thunder',
 'BRK': 'Brooklyn Nets',
 'NOP': 'New Orleans Pelicans',
 'NYN': 'New York Nets',
 'CHH': 'Charlotte Hornets'}

In [85]:
combined_data["Team"] = combined_data["Tm"].map(nicknames)

/var/folders/dy/0p2_mb093ps8390h87cvhc6m0000gn/T/ipykernel_25379/2944803638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data["Team"] = combined_data["Tm"].map(nicknames)

In [86]:
combined_data

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,22.0,LAL,82.0,1.0,18.8,2.5,4.7,0.539,...,0.6,0.6,1.2,2.8,6.4,1986,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,23.0,LAL,79.0,72.0,28.4,4.0,7.4,0.538,...,0.9,1.0,1.3,2.2,10.8,1987,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,24.0,LAL,82.0,64.0,32.1,3.9,7.8,0.503,...,1.1,0.5,1.5,2.5,11.4,1988,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,25.0,LAL,82.0,82.0,30.6,4.9,9.2,0.529,...,1.1,0.7,1.5,2.1,13.3,1989,0.0,0.0,0.0,Los Angeles Lakers
4,A.C. Green,PF,26.0,LAL,82.0,82.0,33.0,4.7,9.8,0.478,...,0.8,0.6,1.4,2.5,12.9,1990,0.0,0.0,0.0,Los Angeles Lakers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,Željko Rebrača,C,29.0,DET,74.0,4.0,15.9,2.6,5.1,0.505,...,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0,Detroit Pistons
22190,Željko Rebrača,C,30.0,DET,30.0,12.0,16.3,2.7,4.8,0.552,...,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0,Detroit Pistons
22191,Željko Rebrača,C,31.0,ATL,24.0,2.0,11.4,1.4,3.2,0.442,...,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0,Atlanta Hawks
22192,Željko Rebrača,C,32.0,LAC,58.0,2.0,16.0,2.3,4.0,0.568,...,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0,Los Angeles Clippers
22193,Željko Rebrača,C,33.0,LAC,29.0,2.0,14.2,1.8,3.3,0.542,...,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0,Los Angeles Clippers

In [87]:
combined_data.isna().sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS         4468
MP            0
FG            0
FGA           0
FG%          70
3P         3950
3PA        3950
3P%        6689
2P            0
2PA           0
2P%         113
eFG%         70
FT            0
FTA           0
FT%         652
ORB        2399
DRB        2399
TRB           0
AST           0
STL        2399
BLK        2399
TOV        3387
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
dtype: int64

In [88]:
stats = combined_data.merge(teams, how="outer", on=["Team", "Year"])
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,22.0,LAL,82.0,1.0,18.8,2.5,4.7,0.539,...,0.000,Los Angeles Lakers,467,62,20,0.756,—,117.3,109.5,6.84
1,Byron Scott,SG,24.0,LAL,76.0,62.0,28.8,6.7,13.0,0.513,...,0.000,Los Angeles Lakers,467,62,20,0.756,—,117.3,109.5,6.84
2,James Worthy,SF,24.0,LAL,75.0,73.0,32.7,8.4,14.5,0.579,...,0.009,Los Angeles Lakers,467,62,20,0.756,—,117.3,109.5,6.84
3,Jerome Henderson,C,26.0,LAL,1.0,0.0,3.0,2.0,3.0,0.667,...,0.000,Los Angeles Lakers,467,62,20,0.756,—,117.3,109.5,6.84
4,Kareem Abdul-Jabbar,C,38.0,LAL,79.0,79.0,33.3,9.6,16.9,0.564,...,0.173,Los Angeles Lakers,467,62,20,0.756,—,117.3,109.5,6.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,Mike Gale,PG,29.0,SAS,67.0,NaN,22.0,2.6,5.6,0.454,...,0.000,San Antonio Spurs,320,41,41,0.500,9.0,119.4,119.7,-0.24
22190,Paul Griffin,C,26.0,SAS,82.0,NaN,22.1,2.1,3.8,0.553,...,0.000,San Antonio Spurs,320,41,41,0.500,9.0,119.4,119.7,-0.24
22191,Sylvester Norris,C,22.0,SAS,17.0,NaN,11.1,1.1,2.5,0.419,...,0.000,San Antonio Spurs,320,41,41,0.500,9.0,119.4,119.7,-0.24
22192,Tim Bassett,PF,28.0,SAS,12.0,NaN,13.7,1.0,2.8,0.353,...,0.000,San Antonio Spurs,320,41,41,0.500,9.0,119.4,119.7,-0.24
22193,Wiley Peck,SF,22.0,SAS,52.0,NaN,12.1,1.4,3.3,0.432,...,0.000,San Antonio Spurs,320,41,41,0.500,9.0,119.4,119.7,-0.24

In [89]:
del stats["Unnamed: 0"]

In [91]:
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [92]:
stats = stats.apply(pd.to_numeric, errors="ignore")
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

## Conclusion

The data has been successfully cleaned, combined, and saved for further analysis.

In [93]:
stats["GB"].unique()

array(['—', '5.0', '14.0', '23.0', '7.0', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '15.0', '1.0', '13.0', '17.0', '3.0', '9.0', '2.0', '35.0',
       '20.0', '11.0', '16.0', '41.0', '12.0', '22.0', '50.0', '10.0',
       '30.0', '34.0', '4.0', '1.5', '51.0', '36.0', '43.0', '39.0',
       '18.5', '31.0', '48.0', '38.0', '32.0', '46.0', '10.5', '27.0',
       '33.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5', '11.5',
       '44.0', '52.0', '56.0', '2.5', '12.5', '53.0', '47.0', '32.5',
       '4.5', '59.0'], dtype=object)

In [94]:
stats["GB"] = stats["GB"].str.replace("—", "0")
stats["GB"] = pd.to_numeric(stats["GB"])
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [96]:
stats.fillna(0, inplace=True)

In [97]:
stats.isna().sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
Team       0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
dtype: int64

In [99]:
stats.to_csv("/Users/paramjaswal/Desktop/NBa/Player_mvp_stats.csv")

In [100]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,22.0,LAL,82.0,1.0,18.8,2.5,4.7,0.539,...,0.0,0.000,Los Angeles Lakers,62,20,0.756,0.0,117.3,109.5,6.84
1,Byron Scott,SG,24.0,LAL,76.0,62.0,28.8,6.7,13.0,0.513,...,0.0,0.000,Los Angeles Lakers,62,20,0.756,0.0,117.3,109.5,6.84
2,James Worthy,SF,24.0,LAL,75.0,73.0,32.7,8.4,14.5,0.579,...,780.0,0.009,Los Angeles Lakers,62,20,0.756,0.0,117.3,109.5,6.84
3,Jerome Henderson,C,26.0,LAL,1.0,0.0,3.0,2.0,3.0,0.667,...,0.0,0.000,Los Angeles Lakers,62,20,0.756,0.0,117.3,109.5,6.84
4,Kareem Abdul-Jabbar,C,38.0,LAL,79.0,79.0,33.3,9.6,16.9,0.564,...,780.0,0.173,Los Angeles Lakers,62,20,0.756,0.0,117.3,109.5,6.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,Mike Gale,PG,29.0,SAS,67.0,0.0,22.0,2.6,5.6,0.454,...,0.0,0.000,San Antonio Spurs,41,41,0.500,9.0,119.4,119.7,-0.24
22190,Paul Griffin,C,26.0,SAS,82.0,0.0,22.1,2.1,3.8,0.553,...,0.0,0.000,San Antonio Spurs,41,41,0.500,9.0,119.4,119.7,-0.24
22191,Sylvester Norris,C,22.0,SAS,17.0,0.0,11.1,1.1,2.5,0.419,...,0.0,0.000,San Antonio Spurs,41,41,0.500,9.0,119.4,119.7,-0.24
22192,Tim Bassett,PF,28.0,SAS,12.0,0.0,13.7,1.0,2.8,0.353,...,0.0,0.000,San Antonio Spurs,41,41,0.500,9.0,119.4,119.7,-0.24
22193,Wiley Peck,SF,22.0,SAS,52.0,0.0,12.1,1.4,3.3,0.432,...,0.0,0.000,San Antonio Spurs,41,41,0.500,9.0,119.4,119.7,-0.24